### ISSUE TITLE
dcmrenamecert doesn't allow spaces

### ISSUE THREAD

**Issue by jared-draper** [ThePrez/DCM-tools#14]
It looks like maybe dcmrenamecert doesn't allow spaces in the label.   

dcmrenamecert --old-label='godaddyinter' --new-label='Go Daddy Secure Certificate Authority - G2'

ERROR: Unknown option 'Daddy'

dcmrenamecert --old-label='godaddyinter' --new-label='GoDaddySecureCertificateAuthority-G2'

SUCCESS!!!

**Comment by ThePrez** [comment]
Thanks for finding! Looks like this is a problem with all arguments for all the dcm* tools that could have a space. I will push a fix shortly.

**Comment by ThePrez** [comment]
I think this is fixed in the `v0.1.1` release. Please test and reopen this issue if needed.

**Comment by jared-draper** [comment]
This worked for me after updating to v0.1.1  Thanks!
