### ISSUE TITLE
Need to explicitly quantify minimum software levels for various features

### ISSUE THREAD

**Issue by ThePrez** [ThePrez/DCM-tools#3]
Some of the APIs used in DCM Tools (and in some cases, particular features of the APIs) rely on certain OS levels. 

We should:
- Identify and document the minimum software requirements for the various features
- Add code checks to provide proper errors if those requirements are not satisfied. For instance, if a user is running on IBM i 7.3 but IBM i 7.4 is needed for a certain operation, it should clearly say so at runtime. 

Will definitely need @tlhaze's help with this!

**Comment by tlhaze** [comment]
The ability to "Renew" a certificate which calls the QycdRenewCertificate API was first available in IBM i 7.4.
Other tasks such as importing certificates via the QykmImportKeyStore API, assigning certificates via the QycdUpdateCertUsage API, and retrieving certificate details via the QycuRetrieveCertificateInfo API are possible on earlier releases.
